# Copyright 2024 The HuggingFace Inc. team. All rights reserved.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

"""
Records a dataset. Actions for the robot can be either generated by teleoperation or by a policy.

Example:

```shell
lerobot-record \
    --robot.type=so100_follower \
    --robot.port=/dev/tty.usbmodem58760431541 \
    --robot.cameras="{laptop: {type: opencv, index_or_path: 0, width: 640, height: 480, fps: 30}}" \
    --robot.id=black \
    --dataset.repo_id=<my_username>/<my_dataset_name> \
    --dataset.num_episodes=2 \
    --dataset.single_task="Grab the cube" \
    --display_data=true
    # <- Optional: specify video codec (h264, hevc, libsvtav1). Default is libsvtav1. \
    # --dataset.vcodec=h264 \
    # <- Teleop optional if you want to teleoperate to record or in between episodes with a policy \
    # --teleop.type=so100_leader \
    # --teleop.port=/dev/tty.usbmodem58760431551 \
    # --teleop.id=blue \
    # <- Policy optional if you want to record with a policy \
    # --policy.path=${HF_USER}/my_policy \
```

Example recording with bimanual so100:
```shell
lerobot-record \
  --robot.type=bi_so_follower \
  --robot.left_arm_config.port=/dev/tty.usbmodem5A460822851 \
  --robot.right_arm_config.port=/dev/tty.usbmodem5A460814411 \
  --robot.id=bimanual_follower \
  --robot.left_arm_config.cameras='{
    wrist: {"type": "opencv", "index_or_path": 1, "width": 640, "height": 480, "fps": 30},
    top: {"type": "opencv", "index_or_path": 3, "width": 640, "height": 480, "fps": 30},
  }' --robot.right_arm_config.cameras='{
    wrist: {"type": "opencv", "index_or_path": 2, "width": 640, "height": 480, "fps": 30},
    front: {"type": "opencv", "index_or_path": 4, "width": 640, "height": 480, "fps": 30},
  }' \
  --teleop.type=bi_so_leader \
  --teleop.left_arm_config.port=/dev/tty.usbmodem5A460852721 \
  --teleop.right_arm_config.port=/dev/tty.usbmodem5A460819811 \
  --teleop.id=bimanual_leader \
  --display_data=true \
  --dataset.repo_id=${HF_USER}/bimanual-so-handover-cube \
  --dataset.num_episodes=25 \
  --dataset.single_task="Grab and handover the red cube to the other arm"
```
"""

import logging
from dataclasses import asdict, dataclass, field
from pathlib import Path
from pprint import pformat

from lerobot.cameras import (  # noqa: F401
    CameraConfig,  # noqa: F401
)
from lerobot.cameras.opencv.configuration_opencv import OpenCVCameraConfig  # noqa: F401
from lerobot.cameras.reachy2_camera.configuration_reachy2_camera import Reachy2CameraConfig  # noqa: F401
from lerobot.cameras.realsense.configuration_realsense import RealSenseCameraConfig  # noqa: F401
from lerobot.cameras.zmq.configuration_zmq import ZMQCameraConfig  # noqa: F401
from lerobot.configs import parser
from lerobot.configs.policies import PreTrainedConfig
from lerobot.datasets.lerobot_dataset import LeRobotDataset
from lerobot.datasets.pipeline_features import aggregate_pipeline_dataset_features, create_initial_features
from lerobot.datasets.utils import combine_feature_dicts
from lerobot.datasets.video_utils import VideoEncodingManager
from lerobot.policies.factory import make_policy, make_pre_post_processors
from lerobot.processor import make_default_processors
from lerobot.processor.rename_processor import rename_stats
from lerobot.robots import (  # noqa: F401
    RobotConfig,
    bi_openarm_follower,
    bi_piper_follower,
    bi_so_follower,
    earthrover_mini_plus,
    hope_jr,
    koch_follower,
    make_robot_from_config,
    omx_follower,
    openarm_follower,
    piper_follower,
    reachy2,
    so_follower,
    unitree_g1 as unitree_g1_robot,
)
from lerobot.scripts.recording_hil import (
    ACPInferenceConfig,
    PolicySyncDualArmExecutor,
    _capture_policy_runtime_state,  # noqa: F401
    _predict_policy_action_with_acp_inference,  # noqa: F401
)
from lerobot.scripts.recording_loop import record_loop
from lerobot.teleoperators import (  # noqa: F401
    TeleoperatorConfig,
    bi_openarm_leader,
    bi_piper_leader,
    bi_so_leader,
    homunculus,
    koch_leader,
    make_teleoperator_from_config,
    omx_leader,
    openarm_leader,
    piper_leader,
    reachy2_teleoperator,
    so_leader,
    unitree_g1,
)
from lerobot.utils.constants import ACTION
from lerobot.utils.control_utils import (
    init_keyboard_listener,
    is_headless,
    sanity_check_bimanual_piper_pair,
    sanity_check_dataset_name,
    sanity_check_dataset_robot_compatibility,
)
from lerobot.utils.import_utils import register_third_party_plugins
from lerobot.utils.recording_annotations import (
    infer_collector_policy_id,
    normalize_episode_success_label,
    resolve_episode_success_label,
)
from lerobot.utils.utils import (
    init_logging,
    log_say,
)
from lerobot.utils.visualization_utils import init_rerun


@dataclass
class DatasetRecordConfig:
    # Dataset identifier. By convention it should match '{hf_username}/{dataset_name}' (e.g. `lerobot/test`).
    repo_id: str
    # A short but accurate description of the task performed during the recording (e.g. "Pick the Lego block and drop it in the box on the right.")
    single_task: str
    # Root directory where the dataset will be stored (e.g. 'dataset/path').
    root: str | Path | None = None
    # Limit the frames per second.
    fps: int = 30
    # Number of seconds for data recording for each episode.
    episode_time_s: int | float = 60
    # Number of seconds for resetting the environment after each episode.
    reset_time_s: int | float = 60
    # Number of episodes to record.
    num_episodes: int = 50
    # Encode frames in the dataset into video
    video: bool = True
    # Upload dataset to Hugging Face hub.
    push_to_hub: bool = True
    # Upload on private repository on the Hugging Face hub.
    private: bool = False
    # Add tags to your dataset on the hub.
    tags: list[str] | None = None
    # Number of subprocesses handling the saving of frames as PNG. Set to 0 to use threads only;
    # set to ≥1 to use subprocesses, each using threads to write images. The best number of processes
    # and threads depends on your system. We recommend 4 threads per camera with 0 processes.
    # If fps is unstable, adjust the thread count. If still unstable, try using 1 or more subprocesses.
    num_image_writer_processes: int = 0
    # Number of threads writing the frames as png images on disk, per camera.
    # Too many threads might cause unstable teleoperation fps due to main thread being blocked.
    # Not enough threads might cause low camera fps.
    num_image_writer_threads_per_camera: int = 4
    # Number of episodes to record before batch encoding videos
    # Set to 1 for immediate encoding (default behavior), or higher for batched encoding
    video_encoding_batch_size: int = 1
    # Video codec for encoding videos. Options: 'h264', 'hevc', 'libsvtav1'.
    # Use 'h264' for faster encoding on systems where AV1 encoding is CPU-heavy.
    vcodec: str = "libsvtav1"
    # Rename map for the observation to override the image and state keys
    rename_map: dict[str, str] = field(default_factory=dict)

    def __post_init__(self):
        if self.single_task is None:
            raise ValueError("You need to provide a task as argument in `single_task`.")


@dataclass
class RecordConfig:
    robot: RobotConfig
    dataset: DatasetRecordConfig
    # Whether to control the robot with a teleoperator
    teleop: TeleoperatorConfig | None = None
    # Whether to control the robot with a policy
    policy: PreTrainedConfig | None = None
    # Display all cameras on screen
    display_data: bool = False
    # Display data on a remote Rerun server
    display_ip: str | None = None
    # Port of the remote Rerun server
    display_port: int | None = None
    # Whether to  display compressed images in Rerun
    display_compressed_images: bool = False
    # Use vocal synthesis to read events.
    play_sounds: bool = True
    # Resume recording on an existing dataset.
    resume: bool = False
    # In policy mode, broadcast the same robot action to the teleop arm via `teleop.send_feedback`.
    policy_sync_to_teleop: bool = False
    # Use parallel dispatch to reduce action broadcast latency when syncing policy to teleop.
    policy_sync_parallel: bool = True
    # Enable S0/S1/S2 intervention state machine when policy + teleop are both available.
    intervention_state_machine_enabled: bool = True
    # Keyboard key used to toggle entering/leaving intervention.
    intervention_toggle_key: str = "i"
    # Whether to capture episode-level success/failure labels from keyboard.
    enable_episode_outcome_labeling: bool = False
    # Keyboard key to mark the current episode as success and end it.
    episode_success_key: str = "s"
    # Keyboard key to mark the current episode as failure and end it.
    episode_failure_key: str = "f"
    # Optional fallback label used when no explicit success/failure key was pressed.
    default_episode_success: str | None = None
    # If True, require explicit or default episode labels before saving.
    require_episode_success_label: bool = False
    # Whether to store step-level collector policy provenance.
    enable_collector_policy_id: bool = False
    # Policy identifier used when action source is policy. If omitted, inferred from policy config.
    collector_policy_id_policy: str | None = None
    # Policy identifier used when action source is human/teleop.
    collector_policy_id_human: str = "human"
    # ACP inference controls for policy-driven recording.
    acp_inference: ACPInferenceConfig = field(default_factory=ACPInferenceConfig)
    # Retry timeout for transient communication errors (seconds). Set to 0 to fail immediately.
    communication_retry_timeout_s: float = 2.0
    # Sleep interval between communication retries (seconds).
    communication_retry_interval_s: float = 0.1
    # During reset loops with no policy/teleop source, send a zero action to the robot.
    reset_to_zero_action: bool = False
    # Optional gripper target used together with reset_to_zero_action during reset loops.
    # This keeps the arm joints at zero while leaving the gripper open for the next episode.
    reset_gripper_pos: float | None = None
    # Run the same reset loop before the first episode. Useful for policy-only eval so episode 0
    # starts from the same home/open-gripper pose as later episodes.
    reset_before_first_episode: bool = False

    def __post_init__(self):
        # HACK: We parse again the cli args here to get the pretrained path if there was one.
        policy_path = parser.get_path_arg("policy")

        if policy_path:
            cli_overrides = parser.get_cli_overrides("policy")

            self.policy = PreTrainedConfig.from_pretrained(policy_path, cli_overrides=cli_overrides)
            self.policy.pretrained_path = policy_path

        if self.teleop is None and self.policy is None:
            raise ValueError("Choose a policy, a teleoperator or both to control the robot")
        sanity_check_bimanual_piper_pair(self.robot, self.teleop)
        if not self.intervention_toggle_key or len(self.intervention_toggle_key) != 1:
            raise ValueError("`intervention_toggle_key` must be a single character.")

        if self.enable_episode_outcome_labeling:
            label_key_bindings = {
                "episode_success_key": self.episode_success_key,
                "episode_failure_key": self.episode_failure_key,
            }
            for key_name, key_value in label_key_bindings.items():
                if not key_value or len(key_value) != 1:
                    raise ValueError(f"`{key_name}` must be a single character.")

            normalized_keys = [
                self.intervention_toggle_key.lower(),
                self.episode_success_key.lower(),
                self.episode_failure_key.lower(),
            ]
            if len(set(normalized_keys)) != len(normalized_keys):
                raise ValueError(
                    "`intervention_toggle_key`, `episode_success_key`, and `episode_failure_key` must be distinct."
                )

        if self.default_episode_success is not None:
            self.default_episode_success = normalize_episode_success_label(self.default_episode_success)

        if not self.collector_policy_id_human:
            raise ValueError("`collector_policy_id_human` must be a non-empty string.")
        if self.acp_inference.use_cfg and not self.acp_inference.enable:
            raise ValueError("`acp_inference.use_cfg=true` requires `acp_inference.enable=true`.")
        if self.acp_inference.cfg_beta < 0:
            raise ValueError("`acp_inference.cfg_beta` must be >= 0.")
        if self.communication_retry_timeout_s < 0:
            raise ValueError("`communication_retry_timeout_s` must be >= 0.")
        if self.communication_retry_interval_s <= 0:
            raise ValueError("`communication_retry_interval_s` must be > 0.")

    @classmethod
    def __get_path_fields__(cls) -> list[str]:
        """This enables the parser to load config from the policy using `--policy.path=local/dir`"""
        return ["policy"]


def _ensure_human_inloop_compatible_features(
    dataset_features: dict[str, dict],
    *,
    action_feature_names: list[str],
) -> None:
    # Keep human-in-loop datasets schema-stable across teleop-only and policy-assisted phases so they can merge.
    dataset_features["complementary_info.policy_action"] = {
        "dtype": "float32",
        "shape": (len(action_feature_names),),
        "names": action_feature_names,
    }
    dataset_features["complementary_info.is_intervention"] = {
        "dtype": "float32",
        "shape": (1,),
        "names": ["is_intervention"],
    }
    dataset_features["complementary_info.state"] = {
        "dtype": "float32",
        "shape": (1,),
        "names": ["state"],
    }


@parser.wrap()
def record(cfg: RecordConfig) -> LeRobotDataset:
    init_logging()
    if cfg.require_episode_success_label and not cfg.enable_episode_outcome_labeling:
        raise ValueError(
            "`require_episode_success_label=true` requires `enable_episode_outcome_labeling=true`."
        )
    logging.info(pformat(asdict(cfg)))
    if cfg.display_data:
        init_rerun(session_name="recording", ip=cfg.display_ip, port=cfg.display_port)
    display_compressed_images = (
        True
        if (cfg.display_data and cfg.display_ip is not None and cfg.display_port is not None)
        else cfg.display_compressed_images
    )

    robot = make_robot_from_config(cfg.robot)
    teleop = make_teleoperator_from_config(cfg.teleop) if cfg.teleop is not None else None

    teleop_action_processor, robot_action_processor, robot_observation_processor = make_default_processors()

    dataset_features = combine_feature_dicts(
        aggregate_pipeline_dataset_features(
            pipeline=teleop_action_processor,
            initial_features=create_initial_features(
                action=robot.action_features
            ),  # TODO(steven, pepijn): in future this should be come from teleop or policy
            use_videos=cfg.dataset.video,
        ),
        aggregate_pipeline_dataset_features(
            pipeline=robot_observation_processor,
            initial_features=create_initial_features(observation=robot.observation_features),
            use_videos=cfg.dataset.video,
        ),
    )
    if cfg.teleop is not None:
        action_names = dataset_features[ACTION]["names"]
        action_names = list(robot.action_features) if action_names is None else list(action_names)
        _ensure_human_inloop_compatible_features(dataset_features, action_feature_names=action_names)
    if cfg.enable_collector_policy_id:
        dataset_features["complementary_info.collector_policy_id"] = {
            "dtype": "string",
            "shape": (1,),
            "names": ["collector_policy_id"],
        }

    dataset = None
    listener = None
    policy_sync_executor = None

    try:
        if cfg.resume:
            dataset = LeRobotDataset(
                cfg.dataset.repo_id,
                root=cfg.dataset.root,
                batch_encoding_size=cfg.dataset.video_encoding_batch_size,
                vcodec=cfg.dataset.vcodec,
            )

            if hasattr(robot, "cameras") and len(robot.cameras) > 0:
                dataset.start_image_writer(
                    num_processes=cfg.dataset.num_image_writer_processes,
                    num_threads=cfg.dataset.num_image_writer_threads_per_camera * len(robot.cameras),
                )
            sanity_check_dataset_robot_compatibility(dataset, robot, cfg.dataset.fps, dataset_features)
        else:
            # Create empty dataset or load existing saved episodes
            sanity_check_dataset_name(cfg.dataset.repo_id, cfg.policy)
            dataset = LeRobotDataset.create(
                cfg.dataset.repo_id,
                cfg.dataset.fps,
                root=cfg.dataset.root,
                robot_type=robot.name,
                features=dataset_features,
                use_videos=cfg.dataset.video,
                image_writer_processes=cfg.dataset.num_image_writer_processes,
                image_writer_threads=cfg.dataset.num_image_writer_threads_per_camera * len(robot.cameras),
                batch_encoding_size=cfg.dataset.video_encoding_batch_size,
                vcodec=cfg.dataset.vcodec,
            )

        # Load pretrained policy
        policy = None if cfg.policy is None else make_policy(cfg.policy, ds_meta=dataset.meta)
        preprocessor = None
        postprocessor = None
        if cfg.acp_inference.enable and cfg.policy is None:
            raise ValueError("`acp_inference.enable=true` requires `policy` to be set.")
        if cfg.policy is not None:
            preprocessor, postprocessor = make_pre_post_processors(
                policy_cfg=cfg.policy,
                pretrained_path=cfg.policy.pretrained_path,
                dataset_stats=rename_stats(dataset.meta.stats, cfg.dataset.rename_map),
                preprocessor_overrides={
                    "device_processor": {"device": cfg.policy.device},
                    "rename_observations_processor": {"rename_map": cfg.dataset.rename_map},
                },
            )

        collector_policy_id_policy = (
            cfg.collector_policy_id_policy
            if cfg.collector_policy_id_policy is not None
            else infer_collector_policy_id(cfg.policy)
        )
        collector_policy_id_human = cfg.collector_policy_id_human

        robot.connect()
        if teleop is not None:
            teleop.connect()
        on_record_connected = getattr(cfg, "_on_record_connected", None)
        if callable(on_record_connected):
            on_record_connected(robot, teleop)

        if cfg.policy_sync_to_teleop:
            if cfg.policy is None:
                raise ValueError("`policy_sync_to_teleop=true` requires `policy` to be set.")
            if teleop is None or isinstance(teleop, list):
                raise ValueError(
                    "`policy_sync_to_teleop=true` requires exactly one teleoperator with send_feedback support."
                )
            policy_sync_executor = PolicySyncDualArmExecutor(
                robot=robot,
                teleop=teleop,
                parallel_dispatch=cfg.policy_sync_parallel,
            )

        listener, events = init_keyboard_listener(
            intervention_toggle_key=cfg.intervention_toggle_key,
            episode_success_key=cfg.episode_success_key if cfg.enable_episode_outcome_labeling else None,
            episode_failure_key=cfg.episode_failure_key if cfg.enable_episode_outcome_labeling else None,
        )

        with VideoEncodingManager(dataset):
            recorded_episodes = 0
            if cfg.reset_before_first_episode and not events["stop_recording"]:
                log_say("Reset the environment before first episode", cfg.play_sounds)

                if robot.name == "unitree_g1":
                    robot.reset()

                record_loop(
                    robot=robot,
                    events=events,
                    fps=cfg.dataset.fps,
                    teleop_action_processor=teleop_action_processor,
                    robot_action_processor=robot_action_processor,
                    robot_observation_processor=robot_observation_processor,
                    teleop=teleop,
                    control_time_s=cfg.dataset.reset_time_s,
                    single_task=cfg.dataset.single_task,
                    display_data=cfg.display_data,
                    policy_sync_executor=policy_sync_executor,
                    intervention_state_machine_enabled=cfg.intervention_state_machine_enabled,
                    collector_policy_id_policy=collector_policy_id_policy,
                    collector_policy_id_human=collector_policy_id_human,
                    acp_inference=cfg.acp_inference,
                    communication_retry_timeout_s=cfg.communication_retry_timeout_s,
                    communication_retry_interval_s=cfg.communication_retry_interval_s,
                    send_zero_action_when_no_source=cfg.reset_to_zero_action,
                    reset_gripper_pos=cfg.reset_gripper_pos,
                )

            while recorded_episodes < cfg.dataset.num_episodes and not events["stop_recording"]:
                events["episode_outcome"] = None
                on_episode_start = getattr(cfg, "_on_record_episode_start", None)
                if callable(on_episode_start):
                    on_episode_start(robot, teleop)

                log_say(f"Recording episode {dataset.num_episodes}", cfg.play_sounds)
                record_loop(
                    robot=robot,
                    events=events,
                    fps=cfg.dataset.fps,
                    teleop_action_processor=teleop_action_processor,
                    robot_action_processor=robot_action_processor,
                    robot_observation_processor=robot_observation_processor,
                    teleop=teleop,
                    policy=policy,
                    preprocessor=preprocessor,
                    postprocessor=postprocessor,
                    dataset=dataset,
                    control_time_s=cfg.dataset.episode_time_s,
                    single_task=cfg.dataset.single_task,
                    display_data=cfg.display_data,
                    display_compressed_images=display_compressed_images,
                    policy_sync_executor=policy_sync_executor,
                    intervention_state_machine_enabled=cfg.intervention_state_machine_enabled,
                    collector_policy_id_policy=collector_policy_id_policy,
                    collector_policy_id_human=collector_policy_id_human,
                    acp_inference=cfg.acp_inference,
                    communication_retry_timeout_s=cfg.communication_retry_timeout_s,
                    communication_retry_interval_s=cfg.communication_retry_interval_s,
                )

                episode_success = None
                if cfg.enable_episode_outcome_labeling:
                    episode_success = resolve_episode_success_label(
                        explicit_label=events.get("episode_outcome"),
                        default_label=cfg.default_episode_success,
                        require_label=cfg.require_episode_success_label,
                    )
                    if events.get("episode_outcome") is None and episode_success is not None:
                        logging.warning(
                            "Episode %s has no explicit success/failure label, defaulting to '%s'.",
                            dataset.num_episodes,
                            episode_success,
                        )

                on_episode_outcome = getattr(cfg, "_on_record_episode_outcome", None)
                if callable(on_episode_outcome):
                    on_episode_outcome(robot, teleop, episode_success)

                # Execute a few seconds without recording to give time to manually reset the environment
                # Skip reset for the last episode to be recorded
                if not events["stop_recording"] and (
                    (recorded_episodes < cfg.dataset.num_episodes - 1) or events["rerecord_episode"]
                ):
                    log_say("Reset the environment", cfg.play_sounds)

                    # reset g1 robot
                    if robot.name == "unitree_g1":
                        robot.reset()

                    record_loop(
                        robot=robot,
                        events=events,
                        fps=cfg.dataset.fps,
                        teleop_action_processor=teleop_action_processor,
                        robot_action_processor=robot_action_processor,
                        robot_observation_processor=robot_observation_processor,
                        teleop=teleop,
                        control_time_s=cfg.dataset.reset_time_s,
                        single_task=cfg.dataset.single_task,
                        display_data=cfg.display_data,
                        policy_sync_executor=policy_sync_executor,
                        intervention_state_machine_enabled=cfg.intervention_state_machine_enabled,
                        collector_policy_id_policy=collector_policy_id_policy,
                        collector_policy_id_human=collector_policy_id_human,
                        acp_inference=cfg.acp_inference,
                        communication_retry_timeout_s=cfg.communication_retry_timeout_s,
                        communication_retry_interval_s=cfg.communication_retry_interval_s,
                        send_zero_action_when_no_source=cfg.reset_to_zero_action,
                        reset_gripper_pos=cfg.reset_gripper_pos,
                    )

                if events["rerecord_episode"]:
                    log_say("Re-record episode", cfg.play_sounds)
                    events["rerecord_episode"] = False
                    events["exit_early"] = False
                    events["episode_outcome"] = None
                    dataset.clear_episode_buffer()
                    continue

                extra_episode_metadata = (
                    {"episode_success": episode_success} if cfg.enable_episode_outcome_labeling else None
                )
                dataset.save_episode(extra_episode_metadata=extra_episode_metadata)
                recorded_episodes += 1
    finally:
        log_say("Stop recording", cfg.play_sounds, blocking=True)

        if dataset:
            dataset.finalize()
            logging.info(
                "To inspect the recorded dataset, run:\n"
                "  lerobot-dataset-report --dataset %s",
                dataset.repo_id,
            )

        if policy_sync_executor is not None:
            policy_sync_executor.shutdown()

        if robot.is_connected:
            robot.disconnect()
        if teleop and teleop.is_connected:
            teleop.disconnect()

        if listener and hasattr(listener, "stop"):
            listener.stop()

        if cfg.dataset.push_to_hub:
            if dataset is not None:
                dataset.push_to_hub(tags=cfg.dataset.tags, private=cfg.dataset.private)
            else:
                logging.warning(
                    "`dataset.push_to_hub=true` was requested, but dataset was not initialized due to an earlier error."
                )

        log_say("Exiting", cfg.play_sounds)
    return dataset


def main():
    register_third_party_plugins()
    record()


if __name__ == "__main__":
    main()
